param([Parameter(Mandatory)][string]$AssemblyPath)
$ErrorActionPreference = 'Stop'
Add-Type -LiteralPath $AssemblyPath
Add-Type -Path "$PSScriptRoot/../scripts/RoySql.cs" -ReferencedAssemblies (@([IO.Directory]::GetFiles("$PSHOME/ref", '*.dll')) + (Resolve-Path -LiteralPath $AssemblyPath).Path)
$examples = [ordered]@{
    'Projection alias' = 'SELECT orderid, unitprice * quantity AS LineTotal FROM [order details]'
    'Expanded nested check' = 'SELECT o.orderid FROM orders o WHERE EXISTS (SELECT 1 FROM [order details] od WHERE od.orderid = o.orderid)'
    'Existing predicates stay intact' = "SELECT orderid FROM orders WHERE orderid BETWEEN 10248 AND 10260 AND customerid != 'ALFKI'"
    'List-wide alias alignment' = 'SELECT unitprice * quantity AS gross, unitprice * quantity * (1 - discount) AS discounted_total, discount AS d FROM [order details]'
}
'# Actual formatter output'
''
'Generated by `tests/examples.ps1`. Synthetic Northwind-shaped SQL, not executed.'
'These are actual outputs for review, not a claim that the style review is complete.'
foreach ($example in $examples.GetEnumerator()) {
    ''
    "## $($example.Key)"
    ''
    'Before:'
    ''
    '```sql'
    $example.Value
    '```'
    ''
    'After:'
    ''
    '```sql'
    [RoySql]::Format($example.Value).TrimEnd("`r", "`n")
    '```'
}
